name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

  ## 🕵️‍♀️ Full commit logs

  - https://github.com/oncokb/oncokb-sop/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
