name-template: 'v$NEXT_MAJOR_VERSION'
tag-template: 'v$NEXT_MAJOR_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

  ## 🕵️‍♀️ Full commit logs

  - https://github.com/genome-nexus/genome-nexus/compare/$PREVIOUS_TAG...v$NEXT_MAJOR_VERSION
