name: Publish Docker Image on Tag
on:
  release:
    types: [published]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v1
      - name: Build and Push Docker Image on Tag
        uses: docker/build-push-action@v1.0.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: oncokb/oncokb-sop
          push: true
          tags: ${{ github.event.release.tag_name:1 }}
