name: Publish Docker Image on Tag
on:
  push:
    tags:
    - '*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cbioportal/oncokb-sop
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
